### ISSUE TITLE
[Error] size mismatch ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [xhp-hust-2018-2011/SS-DCNet#3]
```
>>> cl2h[:,:,rx::rate,ry::rate] = chigh[:,:,rx::rate,ry::rate]*clow
RuntimeError: The size of tensor a (23) must match the size of tensor b (22) at non-singleton dimension 3
```

I think the problem in the input size of the images, so i was asking what was the input sizes and how to control it ?

**Comment by ZhaozwTD** [comment]
I have the same RuntimeError with MohamedAliRashad that is  "RuntimeError: The size of tensor a (8) must match the size of tensor b (7) at non-singleton dimension 3" when I infer single image.

**Comment by xhp-hust-2018-2011** [comment]
Make sure you have padded the image to be divisible by 64.

**Comment by xhp-hust-2018-2011** [comment]
The padding is achieved in load_data_V2.py  line 69,  'image = get_pad(image,DIV=64)'.

**Comment by MohamedAliRashad** [comment]
@xhp-hust-2018-2011 
Thanks.
